### ISSUE TITLE
add run_if: .IsCI

### ISSUE THREAD

**Issue by viktorbenei** [bitrise-steplib/steps-xamarin-user-management#8]
there's no point in running it locally

**Comment by viktorbenei** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;FcMzC5iv&#x2F;979-xamarin-user-management-add-run-if-isci"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> xamarin user management - add run_if: .IsCI</a>

**Comment by godrei** [comment]
Solved in [v 1.0.3](https://github.com/bitrise-steplib/steps-xamarin-user-management/releases/tag/1.0.3), will be available in the steplib in couple of hours.
